INSERT INTO department (dep_name) VALUES 
("Produce"), 
("Cashiers"), 
("Meat"), 
("Deli"), 
("Bakery"), 
("Janitorial");

INSERT INTO roles ( role_name, salary, department_id) VALUES  
("Produce Manager", 40000.00, 1), 
("Cashiers Manager", 40000.00, 2), 
("Meat Manager", 50000.00, 3), 
("Deli Manager", 50000.00, 4), 
("Bakery Manager", 45000.00, 5), 
("Produce Clerk", 35000.00, 1), 
("Cashier", 35000.00, 2), 
("Meat Clerk", 35000.00, 3), 
("Deli Clerk", 35000.00, 4), 
("Baker", 35000.00, 5), 
("Janitor", 35000.00, 6);

INSERT INTO employee (first_name, last_name, role_id) VALUES  
("Guy", "Fieri", 1), 
("Bobby", "Flay", 2), 
("Gordon", "Ramsay", 3), 
("Jamie", "Oliver", 4), 
("Emeril", "Lagasse", 5), 
("Anthony", "Bourdain", 6), 
("Buddy", "Valastro", 7), 
("Rachael", "Ray", 8), 
("Alton", "Brown", 9), 
("Ina", "Garten", 10), 
("Giada", "De Laurentiis", 1), 
("Ree", "Drummond", 2), 
("Sunny", "Anderson", 3), 
("Marcela", "Valladolid", 4), 
("Ayesha", "Curry", 5), 
("Nigella", "Lawson", 6), 
("Trisha", "Yearwood", 7), 
("Paula", "Deen", 8), 
("Sandra", "Lee", 9), 
("Alex", "Guarnaschelli", 10),
("Anne", "Burrell", 11);
("Rachael", "Ray", 5), 
("Alton", "Brown", 6), 
("Ina", "Garten", 7), 
("Giada", "De Laurentiis", 1), 
("Ree", "Drummond", 2), 
("Sunny", "Anderson", 3), 
("Marcela", "Valladolid", 4), 
("Ayesha", "Curry", 5), 
("Nigella", "Lawson", 6), 
("Trisha", "Yearwood", 7), 
("Paula", "Deen", 8), 
("Sandra", "Lee", 9), 
("Alex", "Guarnaschelli", 10),
("Anne", "Burrell", 11);